const Estudio = {
  id: null,
  afiliado_id: null,
  tipo_identificacion: null,
  identificacion: null,
  nombre1: null,
  nombre2: null,
  apellido1: null,
  apellido2: null,
  fecha_nacimiento: null,
  acudiente: null,
  sexo: null,
  celular: null,
  celular2: null,
  email: null,
  eps_id: null,
  tipo_afiliacion: null,
  direccion: null,
  departamento_id: null,
  municipio_id: null,
  barrio_id: null,
  tipo_poblacion: null,
  institucion_muestra: null,
  fecha_estudio: null,
  justificacion: null,
  programa_id: null,
  evento_id: null,
  user_id: null,
  destino: null,
  estado_proceso: null,
  regimen_especial: null,
  edad: null,
  estado_afiliado: null,
  observaciones: null,
  muestras: []
}

export default Estudio
