version: '3'

services:
    web:
        image: nginx:alpine
        volumes:
            - ./dist:/usr/share/nginx/html
            - ./default.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:8080"
        restart: always
