const Vacunacion = {
    id: null,
    afiliado_id: null,
    tipo_identificacion: null,
    identificacion: null,
    apellido1: null,
    apellido2: null,
    nombre1: null,
    nombre2: null,
    fecha_nacimiento: null,
    direccion: null,
    telefono: null,
    email: null,
    priorizacion_id: null,
    eps_id: null,
    fecha_dosis_1: null,
    fecha_dosis_2: null,
    user_id: null,
    municipio_id: null,
    departamento_id: null,
    sexo: null,
    telefono2: null,
    fecha_expedicion: null,
    discapacidad: null,
    cual_discapacidad: null,
    puede_desplazarse: null,
    intencion_vacuna: null,
    porque_no_vacuna: null,
    barrio_id: null,
    coordenadas: null,
    mivacuna: null,
    estado_gestacion: null,
    comorbilidades_vacunacion: [],
    presenta_covid: null,
    // objetos
    edad: null,
    eps: null
}

export default Vacunacion