const Referencia = {
  id: null,
  tipo_identificacion: null,
  identificacion: null,
  nombre1: null,
  nombre2: null,
  apellido1: null,
  apellido2: null,
  fecha_nacimiento: null,
  sexo: null,
  celular: null,
  tipo_poblacion: null,
  eps_id: null,
  tipo_afiliacion: null,
  direccion: null,
  departamento_id: null,
  municipio_id: null,
  fecha_orden: null,
  fecha_solicitud: null,
  afiliado_id: null,
  departamento_prestador_origen: null,
  municipio_prestador_origen: null,
  codigo_prestador_origen: null,
  codigo_cie10_ingreso: null,
  modservicio_id: 2,
  observaciones: null,
  orden_medica_id: null,
  historia_clinica_id: null,
  user_id: null,
  estado_id: null,
  codigo_cie10_egreso: null,
  codigo_prestador_egreso: null,
  estado_egreso: null,
  fecha_egreso: null,
  codigo_cup: null,
  motivo_anulacion_id: null,
  // Sin referencia tabla
  tipo_id: null,
  hora_solicitud: null,
  hora_orden: null,
  barrio_id: null,
  email: null,
  edad: null,
  regimen_especial: null,
  medio_solicitud: null,
  codigo_especialidad: null
}

export default Referencia
